const extraStyle=document.createElement('link');extraStyle.rel='stylesheet';extraStyle.href='enhancements.css';document.head.appendChild(extraStyle);
const portrait=document.querySelector('.portrait');if(portrait){portrait.insertAdjacentHTML('beforeend','<span class="portrait-badge backend">Java + Spring Boot</span><span class="portrait-badge ai">Python + Applied AI</span>')}
const metrics=document.querySelector('.metrics');if(metrics){metrics.insertAdjacentHTML('afterend',`<section class="recruiter-snapshot" aria-labelledby="snapshot-title"><div class="shell"><div class="snapshot-head reveal"><div><p class="eyebrow">Recruiter snapshot</p><h2 id="snapshot-title">Where I create value.</h2></div><p>A quick view of the roles and engineering problems where my experience has the strongest fit.</p></div><div class="snapshot-grid"><article class="snapshot-card reveal" data-index="01"><span class="fit">Primary focus</span><h3>Backend & platform engineering</h3><p>Java, Spring Boot, APIs, event-driven systems, workflow platforms and production ownership.</p></article><article class="snapshot-card reveal" data-index="02"><span class="fit">Applied intelligence</span><h3>AI-enabled products</h3><p>Python, enterprise chatbots, RAG, multimodal retrieval and grounded LLM experiences.</p></article><article class="snapshot-card reveal" data-index="03"><span class="fit">Engineering approach</span><h3>Modernization & optimization</h3><p>Database upgrades, workflow-volume reduction and maintainable cloud-native delivery.</p></article></div></div></section>`)}
const progress=document.querySelector('.progress'),menu=document.querySelector('.menu-button'),nav=document.querySelector('.nav-links');
const updateProgress=()=>{const h=document.documentElement;const range=h.scrollHeight-h.clientHeight;progress.style.width=`${range?100*h.scrollTop/range:0}%`};addEventListener('scroll',updateProgress,{passive:true});updateProgress();
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open)});nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu?.setAttribute('aria-expanded','false')}));
const reveals=document.querySelectorAll('.reveal');const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revealObserver.unobserve(e.target)}}),{threshold:.1});reveals.forEach(el=>revealObserver.observe(el));
const sections=[...document.querySelectorAll('main section[id]')],navAnchors=[...document.querySelectorAll('.nav-links a')];const sectionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){navAnchors.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${entry.target.id}`))}}),{rootMargin:'-25% 0px -65% 0px'});sections.forEach(s=>sectionObserver.observe(s));
document.querySelectorAll('.filters button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filters button').forEach(b=>b.classList.remove('active'));button.classList.add('active');const filter=button.dataset.filter;document.querySelectorAll('.skill-cloud span').forEach(skill=>skill.classList.toggle('hidden',filter!=='all'&&skill.dataset.category!==filter))}));
document.querySelectorAll('.case').forEach(item=>item.addEventListener('toggle',()=>{if(item.open){document.querySelectorAll('.case[open]').forEach(other=>{if(other!==item)other.open=false})}}));
